spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23li9EeXfXfc3JEhJr
            client-secret: c9ad5f65c5765b8b5c8b2da314b3c4065d05b51f
            scope:
              - read:user
              - user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user

  mail:
    host: smtp.gmail.com
    port: 587
    username: hoangdinhdung0205@gmail.com
    password: tlcednddbpagetmk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  config:
    activate:
      on-profile: dev

  devtools:
    add-properties: true

  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}
    title: Backend service
    version: 1.0.0

jwt:
  expiryHour: 1
  expiryDay: 15
  accessKey: ${JWT_SECRET_KEY}
  refreshKey: ${JWT_SECRET_KEY}
